name: nacht_sources_annotations
description: A starting point for Dart libraries or applications.
version: 0.2.1+2
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
