name: nacht_sources
description: The collection of sources used in nacht app
version: 0.2.11

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  dio: ^5.1.0
  equatable: ^2.0.5
  html: ^0.15.1
  intl: ^0.18.0
  rechron: ^0.2.0
  stream_channel: ^2.1.0

dev_dependencies:
  lint: ^2.0.1
  mockito: ^5.3.2
  test: ^1.20.0
