targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:nacht_sources_dev/builder.dart"
    builder_factories: ["crawlerCollectorBuilder"]
    build_extensions: { "$lib$": [".g.dart"] }
    auto_apply: dependents
    build_to: source
